version: "3"
services:
  gingerbread_postgres:
    image: postgres:13.3
    container_name: play-scala-myapp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54320:5432"
    restart: unless-stopped
